# Generated by Django 2.2 on 2020-03-11 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=150)),
                ('last', models.CharField(max_length=150)),
                ('shipping1', models.CharField(max_length=150)),
                ('shipping2', models.CharField(max_length=150)),
                ('shipping3', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.IntegerField()),
                ('credit_number', models.FloatField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnumber', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=150)),
                ('rating', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('price', models.FloatField()),
                ('bluetooth', models.CharField(max_length=200)),
                ('uptime', models.CharField(max_length=200)),
                ('list_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.List')),
            ],
        ),
    ]
