# Generated by Django 2.2 on 2020-03-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='list_type',
        ),
        migrations.AlterField(
            model_name='items',
            name='rating',
            field=models.FloatField(),
        ),
    ]
